### ISSUE TITLE
forward selected messages

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#74]
while signal allows forwarding only one message, we should change the ui to forward multiple selected message, the core supports this via dcContext.forwardMsgs(int msg_ids[], int chat_id);

**Comment by florianhaar** [comment]
Will tackle that one today

**Comment by r10s** [comment]
great :)

**Comment by florianhaar** [comment]
implemented the function to forward multiple selected message to a single person. It is not possible to forward the messages to a group, because there is no easy way to get the groups into the ContactSelectionListFragment. Or is there an easy way, but I don't find it? Maybe the DcContactsLoader.java is a good place to add the groups just with a parameter set to true.

**Comment by r10s** [comment]
@florianhaar great that you push this forward.

i think it is better to allow the users selecting a _chat_ instead of a contact on forwarding. this way, groups are no issues - and i think most times, one will forward to users one is already in contact with. using the normal chat view for forwarding also give a nice sorting.

not sure if the existing ConversationList already offers an option for this. if not i would suggest to realize this by an additonal "extra" as `intent.putExtra(ConversationListActivity.SELECT_CHAT, true);` or so; the result of the activity will be any chat_id then.

maybe it is possible to keep the "+" button in a way so that new chats (at least 1:1 chats) can be created this way; however, i would regard this as the next step then.

**Comment by florianhaar** [comment]
@r10s I try to implement the ConversationList instead of the ContactList. And I think there should be a way to start a new chat. For example if I have just one chat with a friend and I want to forward a message to another friend than I just would see the chat of my first friend and I have no way to forward it to someone else ;-) But for the beginning I will just implement the ConversationList, because it could be a bit complicated.

**Comment by r10s** [comment]
@florianhaar for sure, it would  be great if one could create a new chat on forwarding directly.

however, if only can do forward-to-contact or forward-to-chat easily, i would go for forward-to-chat for now. 
- chats are typically more often used than created
- there is a workaround if a chat is missing (create the chat before forwarding), but there is no workaround if we could only forward to contacts
- we could add a create-chat-on-forward-function later rather seamlessly
- it's the same ui for the user

**Comment by florianhaar** [comment]
@r10s Now it is possible to forward messages to active chats.

**Comment by r10s** [comment]
great :) there is the same crash on my device as for #147, apart from that i would change the title of the activitiyto "forward messages".

**Comment by Boehrsi** [comment]
The title is now adjusted. @r10s everything should work now as intended.

**Comment by r10s** [comment]
just tested things, works as expected for me :) i think we can close this now. 

next iteration somewhen in the future might be to allow searching/createChat from withing the forward/share activity, but for now it is fine.

follows up #175
