### ISSUE TITLE
add qr show+scan activities

### ISSUE THREAD

**Issue by r10s** [deltachat/deltachat-android-ii#79]
the core offers easy methods to verify groups and contacts out-of-band (aka two-factor-auth) via QR codes.

the general flow is: 

- one device, the "inviter", shows a QR code with the string content as returned by [string=getSecurejoinQr(chat_id)](https://c.delta.chat/classdc__context__t.html#aeec58fc8a478229925ec8b7d48cf18bf)
- a second device, the "joiner" scans the QR code and passes the scanned string to [dcContext.checkQr(string)](https://c.delta.chat/classdc__context__t.html#a34a865a52127ed2cc8c2f016f085086c), and if it is a secure-join request, to [joinSecurejoin(string)](https://c.delta.chat/classdc__context__t.html#ae49176cbc26d4d40d52de4f5301d1fa7) then (checkQr() also recognized other actions, btw)
- after that, a process of some messages sending back and forth is started. the ui gets information about this through the events [DC_EVENT_SECUREJOIN_INVITER|JOINER_PROGRESS](https://c.delta.chat/group__DC__EVENT.html#gae1b19779138b8ea63d1b6a5b450c181a)

in the old telegram-codebase, all this is handled by the activities [QRscanActivity](https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/java/com/b44t/messenger/QRscanActivity.java) and [QRshowActivity](https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/java/com/b44t/messenger/QRshowActivity.java).

i think the base-classes of these activities need to be adapted and also the permission stuff.

moreover, the `import com.google.zxing.*` should work (this is the used lib for doing QR+code+scan+show, "zxing" stands for "zebra crossing" :)

i would make the scan-activity accessible by a "qr icon" (eg. [this one](https://github.com/deltachat/deltachat-android/blob/master/MessengerProj/src/main/res/drawable-xhdpi/ic_ab_qr.png) from the old code base) and the first item in the main menu should read "Show QR verify code" and open the show-activity.

**Comment by Boehrsi** [comment]
Will start porting this feature tomorrow.

**Comment by Boehrsi** [comment]
Showing the QR-code now works, I just need to add it at some other places. Scanning also works, but I have to add some UI information for the user, regarding the state of the process (like implemented in the ChatlistActivity in onActivityResultFragment() in the old client). But overall everything seems to work.

**Comment by r10s** [comment]
cool :)

looking forward to test this out :)

**Comment by testbird** [comment]
@Boehrsi Maybe see if you can implement this better in one "activity": https://github.com/deltachat/deltachat-core/issues/247

**Comment by r10s** [comment]
hi @testbird - we should not go back to discussion/feature-request level here currently.

although enhancements may make sense, and probably will come, the most important thing _currently_ is to get android-dev running and stable so that it can replace the current app.

there are tons of good ideas, however, please note that we do not have endless resources ;)

so, i think it makes sense to try to port the existing activities just "as it".

**Comment by testbird** [comment]
Mostly things are only hard if you're not up to them, so it totally depends on @Boehrsi's flexibility and capacity.

**Comment by testbird** [comment]
I mean experience has shown, much can be gained by using even scarce ressources to solve things that are more easy *in the right moments*, and more is lost or sunk by living with flaws or even engage in  cutting down endevours that only lead to things coming back harder if not fail.

**Comment by r10s** [comment]
it's just that https://github.com/deltachat/deltachat-core/issues/247 _does not solve the same problems_ that are solved by https://countermitm.readthedocs.io/en/latest/

**Comment by hpk42** [comment]
On Mon, Oct 15, 2018 at 16:26 -0700, testbird wrote:
> (Right, I brought that up for discussion elsewere. It isn't sure if the lab feature solves anything without introducing two new riscs.)
> 
> But the plain two-way fingerprint scanning would solve the problem of users not having an easy way to set up contacts, the optional lab feature does currently not solve anything for users. I think it is better to keep it disabled to not risk the deltachat reputation, but use the already implemented widgets to ship the established OOB two-way fingerprint scanning method to the users.

Not quite true. "Simple Two-way scanning" would not provide a way to easily
construct "verified groups" which has been user-tested positively 
a number of times now.  Also there are countermitm modifications 
upcoming that allow remote contact or group setup through "secondary" channels
and not just QR-codes (Signal messages, usb-stick etc.).

**Comment by Boehrsi** [comment]
@testbird For the moment I'm trying to port the existing flow and further extensions / optimizations should be done later, as I'm don't think I'm familiar enough with the whole flow and the core to improve the current workflow.

**Comment by Boehrsi** [comment]
Needs a final test with @florianhaar tomorrow to check if the UI behaves as requested, but it should be more or less ready. @r10s I would ask you to review that one, as I don't want to mess up those security things. I will ping you tomorrow when everything is "ready".

**Comment by r10s** [comment]
@Boehrsi cool :) and, yes, please ping me tomorrow :)

**Comment by Boehrsi** [comment]
I added a "final commit" (all old ones are obsolete now) on https://github.com/deltachat/deltachat-android-ii/tree/qr-verify-79 branch. It seems to be working (tested it with @florianhaar ) and it also uses a similar UI to the old Delta app. 
One thing is missing and I think it would be better if you add this @r10s. After a successful scanning of the QR code, when the ConversationActivity should get opened (see TODO's in the mentioned commit), the app crashes due to a missing contact ID. In the old UI we only needed the thread ID it seems. As I don't really know how to get the needed information from the core there I would ask you to finish this last part.

**Comment by r10s** [comment]
@Boehrsi @florianhaar thanks for the work and for the infomation, i will have a look at it

**Comment by r10s** [comment]
have just rebased the branch on master

**Comment by r10s** [comment]
@Boehrsi @florianhaar cool, very good pass. after moving starting the activity ConversationActivity.class back to the main thread, basically everything works.

moreover, we're listening also to the DC_EVENT_SECUREJOIN_JOINER_PROGRESS events and update the text on the joiner side (the that that has scanned). 

merged in https://github.com/deltachat/deltachat-android-ii/pull/91 , so, we're on master again :)

what's left is:

- adding a button "Show QR verify code" beside the button "Add member" in the GroupCreateActivity when a verified group should be created.
- a click on this button should open the QrShowActivity as usual then

after that, this issue can be closed an i would suggest #92 as the next one (as this also affects GroupCreateActivity (or, _Edit_, then)

**Comment by Boehrsi** [comment]
Will add the missing stuff now :).

**Comment by Boehrsi** [comment]
Added the requested changes.

**Comment by Boehrsi** [comment]
As requested closing this an starting with #92 @r10s .

**Comment by r10s** [comment]
@Boehrsi perfect :)

**Comment by testbird** [comment]
> Not quite true. "Simple Two-way scanning" would not provide a way to easily construct "verified groups"

I absolutely never claimed that two-way scanning would create "verfied groups".

In the contrary, the "nextleap" (half-leap) method, based on *seen contact data* (keys actually never compared/verified, only some key-random pair recongnition) actually never constructs anything worth to call a "verified group". It's trusting the matching contact data, to introduce and replace contact data of other contacts (full trust delegation or drop).

But there could be an option with two-way scanned contacts, to accept "introduced-by" contacts that a truly (two-way scanned) verified contact has claimed to have successfully verified (unproven trust).

> countermitm modifications upcoming that allow remote contact or group setup through "secondary" channels and not just QR-codes (Signal messages, usb-stick etc.).

Seems like a good idea to me, using non-transient media will absolutely make it clear that the nextleap method is only a contact/group setup and tracking method, not to be confused with a key verification or security method. (And thus needs to adjust to correct wording.) In the UI the right word to make the nextleap features available would be as a new contact/group creation option (i.e. a correctly termed "contact request" option), not as a contact/key verification option.

**Comment by hpk42** [comment]
Hello Testbird, 

this is a longer mail (also an issue-reply) ... hope it helps
to relax and focus the discussions around what i currently call
the "verification complex".

On Wed, Nov 07, 2018 at 08:38 -0800, testbird wrote:
> > Not quite true. "Simple Two-way scanning" would not provide a way to easily construct "verified groups"
> 
> I absolutely never claimed that two-way scanning would create "verfied groups".

hum, you claimed that the labs feature "solves anything without introducing new risks".
I just wanted to say here that the labs features introduces verified groups
which, however in need of changing, are an interesting feature.

I agree that setting up contacts by two scans should be a supported work flow
at some point.  It allows to establish contact without any network.  Currently,
depending on provider policies and state, and probably also due to some bug,
the verification protocol takes longer than we'd like it to take. 

> In the contrary, the "nextleap" (half-leap) method, based on *seen contact data* (keys actually never compared/verified, only some key-random pair recongnition) actually never constructs anything worth to call a "verified group". It's trusting the matching contact data, to introduce and replace contact data of other contacts (full trust delegation or drop).

The whole discussion around "verified groups" remains open.  
Your critiques and takes on the matter are appreciated ;)
In Kyiv we also got user-testing results that
were critical of some aspects of the UX around verification.  
We also regularly had and have discussions with researchers
from the EPFL in Lausanne, Switzerland, particularly regarding
privacy and security issues. 

The whole "verification complex" which includes UX, implementation
and crypto questions, is no easy one.  There is a lot of traditional
thinking which focuses on crypto-protocols and verifying keys against
"global super-power" adversaries.  Most people under actual repression,
torture and imprisoning or getting-killed threats are rather
confronted with less powerful local adversaries. 

PGP's Web-of-Trust provided a historic example of how
designed-by-secure-crypto can fail to actually protect people at all.
While PGP is heavily used for securing the internet through
signing/verification of software packages which drive the majority of
internet services ... it is much less used for e-mail encryption. 
DeltaChat is helping to change that and also explores new ways
to prevent network adversaries from observing communicatoins
(through eg MITM key exchange). UX, Crypto and Impl considerations
inform each other and no single aspect principally tops the others. 
If crypto is technically secure but can not provide UX that people
can handle accordingly, then it turns into something actually insecure. 

> But there could be an option with two-way scanned contacts, to accept "introduced-by" contacts that a truly (two-way scanned) verified contact has claimed to have successfully verified (unproven trust).
> 
> > countermitm modifications upcoming that allow remote contact or group setup through "secondary" channels and not just QR-codes (Signal messages, usb-stick etc.).
> 
> Seems like a good idea to me, using non-transient media will absolutely make it clear that the nextleap method is only a contact/group setup and tracking method, not to be confused with a key verification or security method. (And thus needs to adjust to correct wording.) In the UI the right word to make the nextleap features available would be as a new contact/group creation option (i.e. a correctly termed "contact request" option), not as a contact/key verification option.

In Kyiv we arrived at the thought to simply present users with
"Setup Contact" and "Setup/invite to Group" choices, not suggesting
up-front much about verification.  By this we can also allow group-join
for "non-verified groups".  It just means that someone can easily join 
and there is one more verification between a pair of people. 

If we are to continue to call "verified groups" ... "verified groups" 
is open for discussion.  Note, however, that those involved in discussing
the verification complex have also a lot of other ongoing things happening. 
There is no single/easy "right" solution so there is no use in fighting
much about such a thing.  It's about evolving our experiences, understandings 
and implementations in conjunction with user-testing and aiming for
something that is better and more useful in practise compared
to what signal/pgp/threema provide ...

hope you manage to join a gathering/meeting at some point.
it would help to sort such and other issues.

**Comment by testbird** [comment]
"concerted contact request" / "accepted concerted contact"?

**Comment by hpk42** [comment]
@testbird, I think your suggestion is better suited for a new topic in the forum
or a real-life discussion at a gathering.

**Comment by testbird** [comment]
The ball is on you side, about to drop.

**Comment by testbird** [comment]
I've sent you a complete draft for a user friendly verification spec, covering the topics that you raised. You are free to bring it forward to a suited forum if you want, or of course show your manners and respond properly.
